spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/gpstrackers
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
server:
  port: 8082