CREATE TABLE gpstrackers(
    "id" SERIAL PRIMARY KEY NOT NULL,
    "name" CHARACTER VARYING(40) NOT NULL,
    "simcard_number" CHARACTER VARYING(12) UNIQUE NOT NULL,
    "device_id" CHARACTER VARYING(20) UNIQUE NOT NULL,
    "login" CHARACTER VARYING (10) NOT NULL,
    "password" CHARACTER VARYING(15) NOT NULL,
    "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    "updated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE coordinates(
  "id" SERIAL PRIMARY KEY NOT NULL,
  "lat" DOUBLE PRECISION NOT NULL,
  "lon" DOUBLE PRECISION NOT NULL,
  "alt" DOUBLE PRECISION NOT NULL,
  "device_id" INT NOT NULL,
  "creation_date" DATE NOT NULL DEFAULT CURRENT_DATE,
  "creation_time" TIME NOT NULL DEFAULT CURRENT_TIME,
  "creation_date_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  CONSTRAINT coordinates_device_id_fk
    FOREIGN KEY ("device_id")
        REFERENCES gpstrackers("id")
            ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE gpstrackers ADD COLUMN "order_card" CHARACTER VARYING (100) UNIQUE ;

ALTER TABLE coordinates ADD COLUMN "order_card" CHARACTER VARYING (100) NOT NULL;